// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqYe7ZI5IkfCh_909kD7PQj4EqcLAUT8k',
    appId: '1:468078459323:web:e5d84472a92c49af4f2c9e',
    messagingSenderId: '468078459323',
    projectId: 'careshare-data',
    authDomain: 'careshare-data.firebaseapp.com',
    databaseURL: 'https://careshare-data-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'careshare-data.appspot.com',
    measurementId: 'G-5MS77VHJDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcK9J0FUWl-Vj9KbyGZpLZlUVbdya1b14',
    appId: '1:468078459323:android:a7b7a60a3280a06a4f2c9e',
    messagingSenderId: '468078459323',
    projectId: 'careshare-data',
    databaseURL: 'https://careshare-data-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'careshare-data.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-sscffOtYOz2JbcVurLxhhFzotMIKTfg',
    appId: '1:468078459323:ios:29634f25c61f9f4b4f2c9e',
    messagingSenderId: '468078459323',
    projectId: 'careshare-data',
    databaseURL: 'https://careshare-data-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'careshare-data.appspot.com',
    iosClientId: '468078459323-vcu38f68lqqoogjh3vnvmtj822rk1043.apps.googleusercontent.com',
    iosBundleId: 'com.careshare',
  );
}
